# Generated by Django 4.2 on 2024-07-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('score', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('subject', models.CharField(choices=[('PC', '物理+化学+不限'), ('P', '物理+不限'), ('H', '历史+不限')], max_length=2, verbose_name='所选科目')),
                ('interest', models.CharField(max_length=3, verbose_name='兴趣(兴趣请输入契合度最高的三个字母)')),
            ],
        ),
    ]
