# Generated by Django 4.2 on 2024-07-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='finalinfo',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='interest',
            field=models.CharField(default='', max_length=3, verbose_name='兴趣(兴趣请输入契合度最高的三个字母)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='rank',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='score',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='subject',
            field=models.CharField(choices=[('PC', '物理+化学+不限'), ('P', '物理+不限'), ('H', '历史+不限')], default='', max_length=2, verbose_name='所选科目'),
        ),
    ]
